// Generated FIX.4.4 definitions.
//
// This file was generated by ironfix-codegen. Do not edit.

/// Decimal type for FIX price, quantity, and amount fields.
pub type FixDecimal = rust_decimal::Decimal;

/// Field tag constants.
pub mod fields {
    /// ClOrdID (tag 11).
    pub const CL_ORD_ID: u32 = 11;
    /// ClOrdId (tag 12).
    pub const CL_ORD_ID_12: u32 = 12;
    /// MsgSeqNum (tag 34).
    pub const MSG_SEQ_NUM: u32 = 34;
    /// PossDupFlag (tag 43).
    pub const POSS_DUP_FLAG: u32 = 43;
    /// Price (tag 44).
    pub const PRICE: u32 = 44;
    /// Side (tag 54).
    pub const SIDE: u32 = 54;
    /// Symbol (tag 55).
    pub const SYMBOL: u32 = 55;
    /// RawData (tag 96).
    pub const RAW_DATA: u32 = 96;
    /// Yield (tag 236).
    pub const YIELD: u32 = 236;
    /// PartyID (tag 448).
    pub const PARTY_ID: u32 = 448;
    /// NoPartyIDs (tag 453).
    pub const NO_PARTY_IDS: u32 = 453;
    /// PartySubID (tag 523).
    pub const PARTY_SUB_ID: u32 = 523;
    /// NoPartySubIDs (tag 802).
    pub const NO_PARTY_SUB_IDS: u32 = 802;
}

/// Message type definitions.
pub mod messages {
    use super::FixDecimal;

    /// Heartbeat message (MsgType=0).
    #[derive(Debug, Clone)]
    pub struct Heartbeat {}

    /// One entry of the NoPartySubIDs (tag 802) repeating group in NewOrderSingleNoPartyIDsEntry.
    #[derive(Debug, Clone)]
    pub struct NewOrderSingleNoPartyIDsEntryNoPartySubIDsEntry {
        /// PartySubID (tag 523).
        pub party_sub_id: String,
    }

    /// One entry of the NoPartyIDs (tag 453) repeating group in NewOrderSingle.
    #[derive(Debug, Clone)]
    pub struct NewOrderSingleNoPartyIDsEntry {
        /// PartyID (tag 448).
        pub party_id: String,
        /// NoPartySubIDs (tag 802) repeating group; its length is the count field.
        pub no_party_sub_ids: Option<Vec<NewOrderSingleNoPartyIDsEntryNoPartySubIDsEntry>>,
    }

    /// NewOrderSingle message (MsgType=D).
    #[derive(Debug, Clone)]
    pub struct NewOrderSingle {
        /// ClOrdID (tag 11).
        pub cl_ord_id: String,
        /// ClOrdId (tag 12).
        pub cl_ord_id_12: Option<String>,
        /// MsgSeqNum (tag 34).
        pub msg_seq_num: Option<i64>,
        /// PossDupFlag (tag 43).
        pub poss_dup_flag: Option<bool>,
        /// Price (tag 44).
        pub price: Option<FixDecimal>,
        /// Side (tag 54).
        pub side: char,
        /// RawData (tag 96).
        pub raw_data: Option<Vec<u8>>,
        /// Yield (tag 236).
        pub r#yield: Option<FixDecimal>,
        /// Symbol (tag 55).
        pub symbol: Option<String>,
        /// NoPartyIDs (tag 453) repeating group; its length is the count field.
        pub no_party_ids: Option<Vec<NewOrderSingleNoPartyIDsEntry>>,
    }

}
